site_name: Why cannot you set up Xdebug?
site_author: Paul Radley
site_description: 'Author: Paul Radley. Personal Blog'
site_dir: build
site_url: https://paulradley.github.com/why-cannot-you-set-up-xdebug
repo_url: https://github.com/paulradley/why-cannot-you-set-up-xdebug

theme:
  name: material
  custom_dir: overrides
  google_html_tag: !ENV GOOGLE_HTML_TAG
  favicon: assets/favicon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/eye
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye-outline
        name: Switch to light mode

plugins:
  - git-revision-date-localized

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list

extra_css:
  - assets/extra.css

extra:
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTIC

nav:
  - Why cannot you set up Xdebug?: index.md